spring:
  application:
    name: 23WelcomeMS

  boot:
    admin:
      client:
        url: http://localhost:1111/

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/



management:
  endpoints:
    web:
      exposure:
        include: '*'
